### ISSUE TITLE
exclude_file does not work 

### ISSUE THREAD

**Issue by raidermax** [DrHyde/rsnapshot#50]
I am on CentOS 6.5 and am using rsnapshot 1.3.1-12 from the EPEL repo. I have made an exclude file that lists directories and files to be included and excluded (+ -) for rsync to use in the config I have. Whenever I perform a backup however, it still backups everything and isnt using the exclude file I made. Rather annoying really...

Command I use to perform the backup
/usr/bin/rsnapshot -c /etc/rsnapshot/necc-data.backup.conf weekly

rsnapshot config file 
http://pastebin.com/qbi0i2m1

rsnapshot exclude file
http://pastebin.com/rn2JQYR0
(Pastebin makes it seem like part of the directory path goes on a new line, but checking with gedit and nano on my machine has it on one line so its fine)

Whats the problem here? I guess a temporary fix is to use the command backup command and list each and every directory manually...although I still need to exclude one or two things

**Comment by bebehei** [comment]
I haven't started reproducing your bug, but it seems to me, that the bug is here at your usage of rsnapshot.

Given that the exclude-file really works (I did not check that yet), you state the following things:
* exclude everything
* exclude again some files
* include some files

For me, this makes no sense, because rsnapshot recommends in this case, that you just use multiple backup-points and throw the include-exclude away, e.g.:
> backup		/var/www/		necc-data.backup/
> backup		/var/named	necc-data.backup/

**Comment by djk20** [comment]
I think the problem here is that rsnapshot "include_file xyz" (which essentially just passes through to "rsync --include-from=xyz") does not handle "+" or "-" prefixes.  For details on how rsync --include-from works, see rsync(1).

So I do not see this as a defect/issue with rsnapshot.

I can think of a few other approaches raidermax could try, like using an include_file with all the "+" directories and an exclude_fle will all the "-" directories; or backup each "+" directory separately (with either global or per-backup exclude_fle or exclude=pattern); or experiment with rsync --filter or similar which should allow a mixture of "+ dir1" and "- dir2" (if you get the spaces & quoting right for extra_rsync_long_args or whatever).

**Comment by raidermax** [comment]
I don't know why you marked this as closed without letting me reply. I already tried making a separate include_file and exclude_file and only having + /directoryhere and - /directhere (pertaining to the include_file and exclude_file) and it also did not work. Also, I am using an exclude_file not an include_file and the only reason I did this was because I was following a CentOS guide http://wiki.centos.org/HowTos/RsnapshotBackups

Hmmm, I guess the last thing I can try is what the first comment suggests. I don't understand why I told it to exclude everything, so I will try removing that out first and see what happens. If that does not work I will abolish the whole exclude_file and just then list something like 

backup      /var/www/       necc-data.backup/
exclude     /var/     necc-data.backup/

in my regular rsnapshot config and see if it works like there. Hopefully it does, I really want to this software working and am really wishing deep down this isnt a bug.

**Comment by bebehei** [comment]
> I don't know why you marked this as closed without letting me reply D:

@djk20 marked this as closed, as we are sure, this is not a rsnapshot-bug.

> I already tried making a separate include_file and exclude_file and only having + /directoryhere and - /directhere (respectively) and it also did not work. Also, I am using an exclude_file not an include_file and the only reason I did this was because I was following a CentOS guide http://wiki.centos.org/HowTos/RsnapshotBackups

Thanks for the link. It seems, that we have to fix a "bug" there. I will contact the Author, when I'm able to find the revision-history in the page.

>Hmmm, I guess the last thing I can try is what the first comment suggests. I don't understand why I told it to exclude everything, so I will try removing that out first and see what happens. If that does not work I will abolish the whole exclude_file and just then list something like

You told it to exclude everything by saying `/*` in the exclude-file.

>backup      /var/www/       necc-data.backup/
exclude     /var/     necc-data.backup/

The exclude-statement, what you are saying here, is not valid. It may go without an error, but you won't get the exlcude to work as wanted. Look in the rsnapshot-manpage for more info about the backup-statements, what I described. Especially look at the configuration example at the bottom.

> in my regular rsnapshot config and see if it works like there. Hopefully it does, I really want to this software working and am really wishing deep down this isnt a bug.

>EDIT 
Alright, so I removed the "exclude     /" and "backup     /     necc-data.backup/" and I copied the contents of my second config to the main rsnapshot config and renamed all that had "include" to "backup" (and I added the necc-data.backup/ entry) and I kept the exclude directories but I did not add the necc-data.bakcup/ entry. Instead of backing up everything it backups only /home and /sbin. I will be able to continue testing tomorrow and give better examples/config files.

It's up to you here. I can't see your config you used. The config-file should be - of course - without errors. It may be the case, that you still have `/*` in excludes. For further support, please consult the rsnapshot-discuss-mailinglist at http://sourceforge.net/p/rsnapshot/mailman/rsnapshot-discuss/. The github-bugtracker is not intended to do support.

But before you do so, I would recommend, you start with a clean rsnapshot.conf-file and enroll it again step by step, while you fully ignore the exclude-statements. After this runs fine, you can exclude your CoD-Tars, etc.

**Comment by raidermax** [comment]
Thank you for all your support, I will try and get a new config going with a new name and everything and perform all the backups without exclude statements and then ill try exclude. Ill make a new thread over at the link you sent me I guess. Thank you though.
